grpc:
  server:
    port: 9090  # gRPC 서버 포트

server:
  port: 8081  # HTTP 서버 포트를 변경

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: seoyeomedev@gmail.com
    password: jwea ohfp lgaq prhp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
